### ISSUE TITLE
Issues with nginx reverse proxy installation

### ISSUE THREAD

**Issue by avdijajp** [TangleBay/hornet-light-installer#1]
Hello, 

i installed the Hornet Node on a Strato Server. Trying to install the nginx reverse proxy it failed with the message shown below. What to do to install nginx to participate on tangle bay?

Thanks in advance for your support. 

Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1071, in perform
    self.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 881, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1141, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:
b''
b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1090, in cleanup
    self.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 881, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1141, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:

**Comment by no8ody** [comment]
Which operation system did you use?

**Comment by avdijajp** [comment]
Hello,

i am using Ubuntu 18.04 LTS 64bi

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: no8ody<mailto:notifications@github.com>
Gesendet: Dienstag, 28. Januar 2020 21:00
An: TangleBay/hornet-light-installer<mailto:hornet-light-installer@noreply.github.com>
Cc: avdijajp<mailto:avdijajp@hotmail.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [TangleBay/hornet-light-installer] Issues with nginx reverse proxy installation (#1)


Which operation system did you use?

**Comment by no8ody** [comment]
Okay, can you please check if you have the latest hli version (0.1.14) and re-run the nginx proxy installer? Please make sure you have started the install with `sudo ./hornet-installer.sh`
